{% set pname = "aihwkit" if cuda_compiler_version == "None" else "aihwkit-gpu" %}
{% set name = "aihwkit" %}
{% set version = "1.0.0" %}
{% set number = 1 %}

package:
  name: {{ pname|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 129799705db6031dda5dfae9f0fea92db944fa7f8d92ff518ae287cfb66b306b

build:
  skip: true  # [win or osx]
  # not yet ready for python 3.12
  skip: true  # [py>=312]
  ignore_run_exports_from:
    - libcusolver-dev  # [(cuda_compiler_version or "").startswith("12")]
    - libcusparse-dev  # [(cuda_compiler_version or "").startswith("12")]
    - pytorch  # [cuda_compiler_version == "None"]
    - pytorch * cuda*  # [cuda_compiler_version != "None"]
    - python
    - cudatoolkit  # [cuda_compiler_version != "None"]
    - sysroot_linux-64
  number: {{ number }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
    - cmake
    - numpy
    - pybind11
    - make
    - mypy
    - libgomp  # [linux]
  host:
    - cuda-version {{ cuda_compiler_version }}  # [cuda_compiler_version != "None"]
    - libcublas-dev                             # [(cuda_compiler_version or "").startswith("12")]
    - libcurand-dev                             # [(cuda_compiler_version or "").startswith("12")]
    - python
    - blas
    - mkl-include
    - pip ==23.0.1
    - scikit-build
    - setuptools                                # Added setuptools for pip build backend
    - pytorch * cuda*    # [cuda_compiler_version != "None"]
    - pytorch          # [cuda_compiler_version == "None"]
    ########################################################################################################################################
    # Needed because PyTorch's ATen `#include`s them                                                                                       #
    # xref: https://github.com/pytorch/pytorch/blob/50efbb9f1e7111b4b6d5b8e9a6064ee9783930be/aten/src/ATen/cuda/CUDAContextLight.h#L6-L16  #
    ########################################################################################################################################
    - libcusolver-dev                           # [(cuda_compiler_version or "").startswith("12")]
    - libcusparse-dev                           # [(cuda_compiler_version or "").startswith("12")]
  run:
    - python
    - blas
    - libopenblas
    - torchvision
    - requests
    - protobuf
    - scipy
    - scikit-learn
    - pytorch * cuda*    # [cuda_compiler_version != "None"]
    - pytorch          # [cuda_compiler_version == "None"]
test:
  imports:
    - aihwkit
    - aihwkit.simulator

about:
  home: https://github.com/IBM/aihwkit
  summary: 'A toolkit for exploring and using the capabilities of in-memory computing devices for AI.'
  license: MIT
  license_file: LICENSE.txt
  doc_url: https://aihwkit.readthedocs.io/
  dev_url: https://github.com/IBM/aihwkit
  
extra:
  recipe-maintainers:
    - kkvtran
    - kaoutar55
    - todd-deshane
    - PabloCarmona
