{% set pname = "aihwkit" if cuda_compiler_version == "None" else "aihwkit-gpu" %}
{% set name = "aihwkit" %}
{% set version = "0.9.1" %}
{% set number = 0 %}

package:
  name: {{ pname|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b86e5ad311225fdad29e9f83f4a5e8e33538677d04080ae180676e208ee96c2c

build:
  skip: true  # [win or osx]
  # not yet ready for python 3.12
  skip: true  # [py>=312]
  missing_dso_whitelist:
    - $RPATH/libtorch_python.so
  number: {{ number }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version != 'None']
    - cmake
    - numpy
    - pybind11
    - make
    - mypy
    - libgomp   # [linux]
  host:
    - python
    - mkl
    - libblas =*=*_mkl
    - mkl-include
    - pip ==23.0.1
    - scikit-build
    - cudatoolkit  # [cuda_compiler_version != 'None']
    - pytorch =*=cuda*   # [cuda_compiler_version != 'None']
    - pytorch      # [cuda_compiler_version == 'None']
  run:
    - python
    - mkl
    - libblas =*=*_mkl
    - torchvision
    - requests
    - protobuf
    - scipy
    - cudatoolkit  # [cuda_compiler_version != 'None']
    - pytorch =*=cuda*   # [cuda_compiler_version != 'None']  
    - pytorch      # [cuda_compiler_version == 'None']
test:
  imports:
    - aihwkit
    - aihwkit.simulator

about:
  home: https://github.com/IBM/aihwkit
  summary: 'A toolkit for exploring and using the capabilities of in-memory computing devices for AI.'
  license: Apache-2.0
  license_file: LICENSE.txt
  doc_url: https://aihwkit.readthedocs.io/
  dev_url: https://github.com/IBM/aihwkit

extra:
  recipe-maintainers:
    - kkvtran
    - kaoutar55
    - todd-deshane
